name: Event Publisher

brokerConfig: |
  bootstrap.servers=localhost:29092

nack: |
  acks=0
  linger.ms=0
  batch.size=131072

ackLeader: |
  acks=1
  linger.ms=0
  batch.size=131072

ackAll: |
  acks=all
  linger.ms=0
  batch.size=131072

idempotent: |
  enable.idempotence=true
  max.in.flight.requests.per.connection=1
  retries=2147483647
  acks=all
  linger.ms=0
  batch.size=131072

outboundTopic: kfk-local.meetup-events

load: 5
duration: 120