---
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper
    healthcheck:
      test: echo srvr | nc zookeeper 2181 || exit 1
      retries: 20
      interval: 10s
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    hostname: kafka
    container_name: kafka
    healthcheck:
      test: nc -vz kafka 9092 || exit 1
      interval: 10s
      retries: 25
      start_period: 20s
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_NUM_REPLICA_FETCHERS: ${KAFKA_NUM_REPLICA_FETCHERS}
      KAFKA_NUM_NETWORK_THREADS: ${KAFKA_NUM_NETWORK_THREADS}
      KAFKA_MESSAGE_MAX_BYTES: ${KAFKA_MESSAGE_MAX_BYTES}
      KAFKA_REPLICA_FETCH_MAX_BYTES: ${KAFKA_REPLICA_FETCH_MAX_BYTES}
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    volumes:
      - ${DIR}/../docker/os-tuning-config/sysctl.conf:/etc/sysctl.conf

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:latest
    volumes:
      - ${DIR}/../monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  event-publisher:
    image: event-publisher:latest
    container_name: event-publisher
    hostname: event-publisher
    environment:
      CHANNEL_MODE: ${CHANNEL_MODE}
      LOG_LEVEL: INFO
      BROKER_CONFIG: |
        bootstrap.servers=kafka:9092
      PRODUCER_TYPE: ${PRODUCER_TYPE}
      OUTBOUND_TOPIC_NAME: kfk-local.meetup-events
    depends_on:
      - event-receiver

  event-receiver:
    image: event-receiver:latest
    container_name: event-receiver
    hostname: event-receiver
    ports:
      - 8854:8854
      - 9292:9292
    environment:
      CHANNEL_MODE: ${CHANNEL_MODE}
      LOG_LEVEL: INFO
      BROKER_CONFIG: |
        bootstrap.servers=kafka:9092
      PARALLEL_CONSUMER_MAX_CONCURRENCY: ${CONSUMER_CONCURRENCY}
      INBOUND_CONFIG: |
        auto.offset.reset=earliest
        enable.auto.commit=false
      INBOUND_TOPIC_NAME: kfk-local.meetup-events

